[project]
name = 'loopbomb-marketplace'
description = ''
authors = []
telemetry = false
cache_dir = './.cache'
requirements = []
[contracts.art-nft-registry]
path = 'contracts/art-nft-registry.clar'
clarity_version = 3
epoch = 3.1

[contracts.artist-profile-manager]
path = 'contracts/artist-profile-manager.clar'
clarity_version = 3
epoch = 3.1

[contracts.royalty-payment-processor]
path = 'contracts/royalty-payment-processor.clar'
clarity_version = 3
epoch = 3.1
[repl.analysis]
passes = ['check_checker']

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false
